# Generated by Django 4.1.7 on 2024-04-09 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0005_delete_consultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('resumo', models.TextField()),
                ('preferencia_alimentar', models.TextField()),
                ('horario_fome', models.TimeField()),
                ('horas_sono', models.TextField()),
                ('tabagismo', models.CharField(choices=[('S', 'sim'), ('N', 'não')], max_length=1)),
                ('frequencia_tabagismo', models.CharField(blank=True, max_length=20, null=True)),
                ('atividade_fisica', models.CharField(choices=[('S', 'sim'), ('N', 'não')], max_length=1)),
                ('atividade', models.CharField(blank=True, choices=[('A', 'academia'), ('N', 'natacao'), ('C', 'corrida'), ('L', 'luta'), ('O', 'outro')], max_length=1, null=True)),
                ('horario_atividade', models.TimeField(blank=True, null=True)),
                ('qtd_dias_atividade', models.IntegerField(blank=True, default=3, null=True)),
                ('local', models.TextField(blank=True, default='Endereço=Alameda Tocantins 330, andar 8')),
                ('comprovante_horas', models.FileField(blank=True, null=True, upload_to='')),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
    ]
