# Generated by Django 4.1.7 on 2024-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_dadosconsulta_delete_consultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('A', 'agendada'), ('C', 'cancelada'), ('F', 'finalizada')], max_length=1),
        ),
    ]
