# Generated by Django 4.1.7 on 2024-04-13 23:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_delete_consultas'),
        ('consultas', '0003_alter_consulta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='numero_pedido',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_horario',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='CodigoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=20000, unique=True)),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 20, 12, 42, 933603))),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.codigopedido'),
        ),
    ]
