# Generated by Django 4.1.7 on 2024-04-14 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_remove_consulta_numero_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 23, 42, 16, 886428)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_horario',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='local',
            field=models.TextField(blank=True, default='Alameda Tocantins 330, andar 8'),
        ),
    ]
