# Generated by Django 4.1.7 on 2024-04-14 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_codigopedido_data_alter_consulta_data_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 15, 36, 58, 167087)),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.codigopedido'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='local',
            field=models.TextField(blank=True, default='São Paulo, Toninho Cerezo 820, andar 8'),
        ),
    ]
