# Generated by Django 4.1.7 on 2024-04-19 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_codigopedido_data_alter_consulta_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 36, 19, 259534)),
        ),
        migrations.AlterField(
            model_name='dadosconsulta',
            name='frequencia_tabagismo',
            field=models.CharField(blank=True, choices=[('1M', '1 maço por dia'), ('2M', '2 maços por dia'), ('M+', 'mais de 2 maços por dia'), ('M-', 'menos de 1 maço por dia')], max_length=2, null=True),
        ),
    ]
