# Generated by Django 4.1.7 on 2024-04-30 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0013_alter_cancelamento_data_alter_codigopedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 23, 26, 49, 701479)),
        ),
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 23, 26, 49, 699460)),
        ),
    ]
