# Generated by Django 4.1.7 on 2024-04-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_alter_cancelamento_data_alter_codigopedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 17, 4, 5, 948616)),
        ),
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 17, 4, 5, 948616)),
        ),
    ]
