# Generated by Django 4.1.7 on 2024-05-11 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0015_alter_cancelamento_data_alter_codigopedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 34, 0, 570562)),
        ),
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 34, 0, 568263)),
        ),
        migrations.AlterField(
            model_name='dadosconsulta',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.consulta'),
        ),
    ]
