# Generated by Django 4.1.7 on 2024-05-12 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0016_alter_cancelamento_data_alter_codigopedido_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 22, 0, 7, 464055)),
        ),
        migrations.AlterField(
            model_name='codigopedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 22, 0, 7, 461567)),
        ),
    ]
