# Generated by Django 4.1.7 on 2024-04-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_consultas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultas',
        ),
    ]
