# Generated by Django 4.1.7 on 2024-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_delete_consultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
