# Generated by Django 4.1.7 on 2024-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_pacientes_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
