# Generated by Django 4.1.7 on 2024-04-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_pacientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospaciente',
            name='taxa_metabolismo_basal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
