# Generated by Django 4.1.7 on 2024-04-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_dadospaciente_taxa_metabolismo_basal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='taxa_metabolismo_basal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
