# Generated by Django 4.1.7 on 2024-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_geradados'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradados',
            name='consultas',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='geradados',
            name='dados_pacientes',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='geradados',
            name='pacientes',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='geradados',
            name='planos_alimentares',
            field=models.IntegerField(default=40),
        ),
    ]
