# Generated by Django 4.1.7 on 2024-04-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_geradados_consultas_geradados_dados_pacientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geradados',
            name='dados_pacientes',
        ),
        migrations.RemoveField(
            model_name='geradados',
            name='planos_alimentares',
        ),
        migrations.AlterField(
            model_name='geradados',
            name='limite',
            field=models.IntegerField(default=80),
        ),
    ]
