# Generated by Django 4.1.7 on 2024-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_remove_geradados_dados_pacientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geradados',
            name='consultas',
        ),
        migrations.RemoveField(
            model_name='geradados',
            name='pacientes',
        ),
        migrations.AlterField(
            model_name='geradados',
            name='limite',
            field=models.IntegerField(default=40),
        ),
    ]
